[project]
name = "mina"
version = "0.0.1"
description = "Mel Inter-phoneme Neural Alignment"
requires-python = ">=3.13"
dependencies = [
    "librosa>=0.11.0",
    "torch>=2.13.0",
    "numpy>=2.4.4",
    "textgrid>=1.6.1",
    "tqdm>=4.70.0",
    "lightning==2.6.5",
    "matplotlib>=3.10.8",
    "tensorboard>=2.20.0",
    "tempdir>=0.7.1",
    "muon-optimizer",
    "pytest>=9.0.3",
    "onnx>=1.22.0",
    "onnxslim>=0.1.94",
    "onnxscript>=0.7.1",
    "rich>=15.0.0",
    "ray[tune]>=2.55.1",
    "ax-platform>=1.2.4",
    "optuna>=4.8.0",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
    { index = "pytorch-cu130", marker = "sys_platform == 'linux'" },
]
muon-optimizer = { git = "https://github.com/KellerJordan/Muon" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
